module.exports = (config) ->
	date = Date.now()
	file = "## HAproxy config file generated by HAapi - #{config.name}@#{date}"
	push = (line) ->
		file = "#{file}\n#{line}"
	pushsub = (line) ->
		file = "#{file}\n    #{line}"
	push "## WARNING: Any manual changes to this file may be overwritten!"
	# globals and defaults
	push config.generalConfig
	for frontend in config.frontends
		push "frontend #{frontend.name}"
		pushsub "bind #{frontend.bind}"
		pushsub "mode #{frontend.mode}"
		for option in frontend.options
			pushsub option
		for acl in frontend.acl
			pushsub "acl #{acl.name} #{acl.cond}"
		for use in frontend.use
			pushsub "use_backend #{use.backend.name} #{use.ifs}"
		pushsub frontend.default_use if frontend.default_use?
	for backend in config.backends
		push "backend #{backend.name}"
		pushsub "balance #{backend.balance}"
		pushsub "mode #{backend.mode}"
		for option in backend.options
			pushsub option
		for server in backend.servers
			pushsub "server #{server.name} #{server.path} #{server.options}"
	return file
